builds:
  - main: main.go
    binary: sealed-secrets-key
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/d-kuro/restart-object/cmd.Revision={{ .ShortCommit }}
